### PR TITLE
Allow string argument passthrough

### LINKED ISSUE #56: Support pass-through of string parameters in user-defined functions
Basically, something like this should be possible:

```
function readfilenormalized(filename, pos)=readfile1(filename, pos)/255
```

Right now, it will throw an error because it thinks all parameters in user-defined functions are doubles. I think one simple way of fixing it could be to allow optional specification of data types in user-defined functions:

```
; pos defaults to ": double" here because nothing is specified.
function readfilenormalized(filename : string, pos)=readfile1(filename, pos)/255
```

### LINKED ISSUE #86: Bug evaluating function parameters
While working on a pull request for a different issue I noticed that the following code fails fails the assert statement, when obviously it should succeed:
``` asm
org $8000
function test(abc,ab) = abc+ab
assert test(1,2) == 3
```
Pull request that contains a fix will be sent shortly.

### PR DESCRIPTION
**Pull request by KevinCathcart**
Fixes #56 without changing the syntax.
The following code (based on the example in that bug) will simply work with this patch.
```
function readfilenormalized(filename, pos) = readfile1(filename, pos)/255
```
The approach is simply checking to see if a function argument is one of the parameters of the user function currently being executed. If it is pass it directly through to function being called. 

This also fixes #86, which I found while coding this. (The fix is the same as was previously used for a similar issue matching the names of the built in functions).

### CODE REVIEW

**Comment by randomdude999** [comment]
You should probably write some tests for this too.

**Comment by KevinCathcart** [comment]
Yeah. I've not yet added any test cases for this. I'm guessing we would want to add the test case for the string pass-through to the v160features.asm test.

I'm not sure if there is a particularly good spot for the bugfix test, or if i should create a functest3.asm.

**Comment by RPGHacker** [comment]
Yeah, I'd personally just add it to v160features.asm. Just one or two simple tests should do.

**Comment by KevinCathcart** [comment]
I've added the passthrough test to v160features.asm, but added the bugfix regression test as a separate test file, because it did not feel right to put that in a features test file.

**Pull request merged**
