### PR TITLE
Don't removerats twice when two autocleans point to the same freespace

### LINKED ISSUE #216: Wrong address when cleaning freespace blocks multiple times
I came across this in GPS where for some reason two label in different freespace blocks had the same address. The simples test case I could find is creating a rom with
<pre>
check bankcross off
org $008000 : rep $80000 : db $00
</pre>

and then patching
<pre>
print "previous test1: $",hex(read3($008000+1))
print "previous test2: $",hex(read3($008004+1))
print "new test1: $",hex(test1)
print "new test2: $",hex(test2)

org $008000
autoclean JML test1

org $008004
autoclean JML test2

freecode
test1: db 1

org $008008
autoclean JML test1

freecode
test2: db 2
</pre>

twice which prints the following:

<pre>
first run:
previous test1: $0
previous test2: $0
new test1: $908008
new test2: $908011

second run:
previous test1: $908008
previous test2: $908011
new test1: $908008
new test2: $908008
</pre>

on the second run, both test1 and test2 have the same address even though they're supposed to be in separate freespace blocks.

edit: I should probably specify that this only happens if you one autoclean is before the freespace command and one after and then another freespace is requested.

Playing around with this a bit more: If test1 is cleaned, then requested then another freespace block is requested and then test1 is cleaned again asar throws an error ` (E5136): Don't autoclean a label at the end of a freespace block, you'll remove some stuff you're not supposed to remove. [autoclean JML test1]`

### PR DESCRIPTION
**Pull request by spooonsss**
Fixes #216

No test added. Since this bug requires existing RATS tags to repro, I don't think the current testing framework would support a test for this.

### CODE REVIEW

**Comment by Alcaro** [comment]
From a cursory glance, this looks like it'll just trade one bug for another, and leak freespace in cases like 
```
;patch1.asm
org $008000
autoclean jsl hijack1
autoclean jsl hijack2

freecode
hijack1:
rtl

freecode
hijack2:
rtl

;patch2.asm
org $008000
autoclean jsl hijack1
autoclean jsl hijack2

freecode
hijack1:
rtl
hijack2:
rtl
```
or, of course, things like autoclean dl or autoclean read3($00f606) (this patch only touches the autoclean jml/jsl handler).

If I remember correctly, autoclean originally ran in the first pass, and the freespace finder was second; can't delete something that's not there yet. Did we leave that model? If yes, was it due to bugs involving lda ForwardLabel : autoclean jsl AnotherLabel?

Proposed proper patch: For each autoclean, loop the list of freespaces created in this patch prior to this point. If that list contains this address, the autoclean target was already deleted and reused, and should not be deleted again.

**Comment by RPGHacker** [comment]
> No test added. Since this bug requires existing RATS tags to repro, I don't think the current testing framework would support a test for this.

Actually, I think there is a way to tell the test suite to a apply a patch twice to the same ROM. We just probably forgot to document it in README.me.

Taking a peak at prot.asm, the syntax seems to be:
```;`+ #2```

**Comment by spooonsss** [comment]
Alcaro is right, that testcase shows a bug introduced. And I forgot to handle `autoclean dl`. I'll rework this.

**Comment by Alcaro** [comment]
Looks good to me, other than the nitpick. Good job wrangling this thing, Asar is a messy tool and this isn't its easiest part.

**Comment by randomdude999** [comment]
i deleted this entire fix in asar2.0, since there rats tags are cleaned during pass 1 and freespaces are allocated at the end of pass 1. which i'm pretty sure avoids the root cause of this bug

**Pull request merged**
