### PR TITLE
Remove unnecessary comment.

### PR DESCRIPTION
**Pull request by cyraid**
Pinging @p4plus2 for the approval as requested from him.

P.S. Happy 2024 A.D. (Anno Domini)

### CODE REVIEW

**Comment by p4plus2** [comment]
@Alcaro @randomdude999 @RPGHacker Thoughts?

Personally, I see little point since this branch has no future release plans.  But as promised in my initial comment i would divert to others to weigh in.

**Comment by Alcaro** [comment]
this entire repo is so full of cursed code it has been forsaken by all gods, including [those it's named after](https://en.wiktionary.org/wiki/asar#Swedish); only the forces of darkness are willing to even approach

if we offend them too, everything's just gonna stop working

remember that pentagram we accidentally damaged last halloween? remember how many chickens we had to sacrifice to get things working again? I'd rather not risk reviving that mess

@p4plus2 satan is everywhere, I think this guy is referring to the Bible version of satan

**Comment by cyraid** [comment]
Do you know of a different satanism? It's pretty obvious what it's referring to. :)

I mean, if you're fine with having a comment that has nothing to do with the code in here, why can't we put "Jesus Christ is Lord. He is the way, the truth, and the life." in there? Maybe a Bible verse?

Why was this comment on a version bump?

**Comment by Alcaro** [comment]
Jesus Christ is the way ... to where? [To Rome?](https://en.wikipedia.org/wiki/All_roads_lead_to_Rome) I don't want to go to Rome, I don't have a passport.

**Comment by RPGHacker** [comment]
To quickly add my two cents on the matter: I say the comment can stay. I'm a firm believer in religious freedom - even if the religion that is being practiced is atheism or satanism (or literally any religion in addition to Christianity). Freedom of religion, in my opinion, also includes the freedom to express your religious beliefs in whatever way you see fit (that isn't obviously discriminating against other people). This is also true if the way you chose for broadcasting your religious beliefs is via a comment in the source code of an SNES assembler. As far as I know, the GPL license (under which Asar is licensed) also doesn't prohibt doing this, so as far as I'm concerned, both from a moral and legal standpoint, there's nothing objectionable about this comment.

Now it's not like I'd go to war over keeping this comment in Asar. At the very least, I'd take the opinion of the other primary maintainers of this repository into consideration, and since none of them ever complained about it and (as far as I'm aware) none of them is a Christian, I'm fine with the comment staying. I can't claim to know enough about copyright law to where I really understand all the ins and outs of the GPL license, but the way I understand it, every person who creates a fork of a GPL-licensed project becomes the copyright holder of that specific fork (under the condition that they can't ever change the license of that fork to anything that isn't GPL), so as far as I understand, I am technically the copyright holder of this specific fork of Asar that is hosted on my GitHub, which presumeably means I'm the person who gets "the final say" on decisions regarding this specific fork. I believe this means as long as I'm fine with that comment, it's free to stay, regardless of what opinions other people might have and regardless of if it might be considered offensive to people who practice Christianity.

Now while I said I wouldn't go to war over keeping this comment, I do lean strongly towards keeping it. One reason for this is simply that I consider it funny and that it feels very true to what I personally perceive work on Asar to feel like. Another (possible even bigger) reason is that this comment doesn't even affect Asar (as in, the application) in any way. It's just a comment that literally gets compiled away when you build Asar. The binary output of Asar won't change regardless of whether the comment exists or not, so Asar (as in, the application) isn't any more or less Christian because of this comment. You might argue that this is a more of an argument against keeping the comment, but I disagree (for all of the reasons stated above).

Now luckily, one other great aspect of the GPL license is that while I might be the copyright holder of this specific fork of Asar, I can't prohibit anyone from creating additional forks of it and gaining the copyright over those forks. So while I might be of the opinion that a comment referencing satanism can stay in this specific fork of Asar, it's also both legally and morally within your right to create a new fork of it that either removes the comment or even changes it to something praising Jesus (as your pull request basically already did). You could rename it to something like "Asar - Christianity-compliant edition". In fact, you don't even need to keep the name "Asar". You could rename it to just "praise_jesus.exe". Not only do you have the right to do so, but I fully encourage you to do it (since, as mentioned above, I fully support freedom of religious expression) - and the fact that people do have the freedom to do this is the final reason for why I think the comment on this specific fork of Asar can stay as is.

It's also worth emphasizing that the fork of Asar being hosted here can't be considered "the" Asar. Rather, it's just "an" Asar. Sure, it might be the most popular and most widely used fork of Asar around by now, but still, it's not THE Asar. It's just the specific fork of Asar that I started. So this specific fork of Asar referencing satanism can't even be considered as "Asar advocating for satanism", as there do exist versions and forks of Asar that do not include the comment. At best, it can only be considered as "this specific fork of Asar advocating for satanism".

**Comment by cyraid** [comment]
I see what you're trying to say, but then why can't you just change it to Praise Jesus Christ if I'm the only one who cares and you guys don't care? It was slapped in a version bump, that's what got me. Why put it in? Seems very out of place.

Jesus is the truth, it's like saying 2+2=4. It's not some cult. It's like, why teach people math then?

I have proof He is real, and you'll all find out in the end when He comes, and I warn you now, if you don't repent and turn to Him, you will greatly suffer.

We can have a longer debate about it if you wish (just don't censor me), and I can tell you about the miracles He's done in my life (I've had my back healed 2 hours after praying to Jesus after suffering for a year), and other incredible prayers He's answered, but in the end I figure: people have no problem worshipping satan (and Santa etc), making games about the devil (diablo), demonic shows, but as soon as someone mentions Jesus and that He is real people go ballistic or mock Him (as seen above).

People most likely wouldn't have mocked Buddha or Zeus if I mentioned those figures.

In the end some might say "don't bring your 'religion' in here", well I say, you already have.

But anyway, like you said, nothing will be changed and you all knew that but I say, I already knew that too.

Our whole time system is based off Jesus. So happy 2024 and 2025 AD (Anno Domini, which means the Year of The Lord, and BC meaning Before Christ).

Take care.

**Comment by RPGHacker** [comment]
I'm not too interested in getting into religious discussions on GitHub of all places, so I won't respond to most things you brought up in detail, but I will clarify that me saying "I won't go to war over this" isn't the same as me saying "I don't care at all". In fact, I DO care about this joke staying where it is, and I DO care about not letting ourselves get coerced into adding a statement for a religion we personally don't believe in to the source code.

**Comment by Ersanio** [comment]
As a user of asar, I'd like to share my two cents.

The comment in question seems similar to something like "here be dragons" just written in a different way. Despite that, the intent feels similar: a playful nod to the challenges of dealing with cursed code.

Sure, the comment could be replaced with something else. However, this raises three issues.

First, the comment is a direct citation of one of the individuals who contributed code to this repository. We cannot go back in time to change what they have said. Producing a new citation for the sole purpose of replacing the current one, would feel very artificial.

Second, this pull request raises a larger, more important question that could actually affect all users. If we start replacing or removing things for potential offense, _where do we draw the line_? Should we rename opcodes such as `BRA` (from the 65816 architecture) or `SEX` (from the SuperFX architecture) while at it? After all, they could evoke certain imaginations and tempt users into sinful thoughts, or seduce them into committing a premarital sin.

Finally, I do not agree with the suggestion of replacing the comment with praising Jesus Christ, as not everyone practices Christianity. I, for example, am Muslim, so that belief does not align with mine. However, Satan (or Iblis) is a rather easily-recognized antagonist of mankind. The fact that _Satan_ is mentioned, and not dragons, emphasizes just how cursed the code is. It's a creative citation that I, for one, can appreciate.

**Comment by Alcaro** [comment]
now look what you did, you woke the Ersanio from His slumber

If the maintainers vote on this, then I will accept the outcome, even if it's contrary to my preference. However, I will expect a fair vote.

I believe that's how all maintainers feel, and what RPG Hacker is trying to say. Going to war over it would mean trying to override the vote.

I would, however, vote yes to your proposed compromise of adding a bible verse below it, if we can find a fitting one. I nominate [John 11:35](https://www.biblegateway.com/passage/?search=John%2011%3A35&version=NIV).

**Comment by cyraid** [comment]
If nothing is offensive then why can't we write "Allah is the devil"?

I vote for "There are only two genders.".

**Comment by trillllian** [comment]
okay that was too much.

**Comment by cyraid** [comment]
Oh so I was censored for saying "Allah is the devil"? Or "there are only two genders"? Hypocrites. You just proved yourselves liars, and that you can only write "offensive" stuff if it aligns with what YOU believe.

**Pull request closed without merging**
